import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex justify-center items-center min-h-screen bg-gray-100">
        {/* 부모 컨테이너: 모바일 크기 유지 */}
        <div className="relative w-full max-w-[480px] min-h-screen bg-white shadow-lg flex flex-col mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}